// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtgo9B0CdINcqOGBUMz6JXJGswUBVUCFs',
    appId: '1:738727811148:web:5922fa6742edb804fcbce9',
    messagingSenderId: '738727811148',
    projectId: 'openote-b6d31',
    authDomain: 'openote-b6d31.firebaseapp.com',
    storageBucket: 'openote-b6d31.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCZDQL2JIPUuiDWpy5KEPhw4-Php3Teqo',
    appId: '1:738727811148:android:7be58b8d2a7327d7fcbce9',
    messagingSenderId: '738727811148',
    projectId: 'openote-b6d31',
    storageBucket: 'openote-b6d31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDjYHtndAcLQiQdUUckyDP8L7pCm4y7co',
    appId: '1:738727811148:ios:26fdc18b8e84776bfcbce9',
    messagingSenderId: '738727811148',
    projectId: 'openote-b6d31',
    storageBucket: 'openote-b6d31.appspot.com',
    iosClientId: '738727811148-lh3nfdt0lnevvvg0ol6nissmtnljnkgr.apps.googleusercontent.com',
    iosBundleId: 'com.example.notivate',
  );
}
